const doWork = async () => {
    throw new Error('Someting went wrong')
    return 'Andrew'
}




console.log(doWork())

